spring: 
  datasource: 
    hikari.minimum-idle: 3
    hikari.maximum-pool-size: 10
    hikari.max-lifetime: 30000 # 不能小于30秒，否则默认回到1800秒
    username: root
    password: a1b2c3
    url: jdbc:mysql://175.24.78.152:3306/emp?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: 
    host: 175.24.78.152
name: wcr

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config: 
    db-config: 
     logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
     logic-delete-value: 1 # 逻辑已删除值(默认为 1)
     logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml    
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
